### ISSUE TITLE
mvcc and icc support? Visual studio support

### ISSUE THREAD

**Issue by GillianGrayson** [bsamseth/cpp-project#12]
Hi!

Very interesting and very helpful repository! Thank you for sharing it!

Do you plan to add support for different compilers and examples of usage for Windows users?

Thank you!

**Comment by bsamseth** [comment]
Glad you have found it helpful!

Windows support hasn't been a priority for me, simply because I don't have access to a windows machine. That said, I would naively expect that it mostly works as is, as CMake is supposed to be somewhat platform independent (with exceptions being spesific compiler flags for coverage builds). 

I've tried this with a couple of different IDES, and every one that supports CMake plays quite nicely with this setup. I've simply opened the folder an pointed at the `CMakeLists.txt` file and it works. I would think the same is true in Windows, but I have no way of testing this at the moment. 

Is there something particular your looking for, or similarly, could you tell me what does _not_ work? If so, perhaps I can figure out how to address it. 

Any additions you would want to make is also greatly appreciated if you want to make a pull request.

**Comment by bsamseth** [comment]
The setup is now tested with Appveyor, and builds without issue under Visual Studio 2017 (probably just as fine for earlier versions if C++17 support is dropped). Build instructions should be readable by looking at [appveyor.yml](https://github.com/bsamseth/cpp-project/blob/master/appveyor.yml), but they should boil down to the exact same usage on Windows as on Linux/macos. It will depend on your setup, where you might want to explicitly choose build system/compiler etc. If used from an IDE, the IDE should be smart enough to handle everything as long as you point to the CMakeLists.txt file. 

As there has not been any response to this in a while, I'm closing the issue. Feel free to repoen if needed.
