### ISSUE TITLE
Add code format target

### ISSUE THREAD

**Issue by ilyar** [bsamseth/cpp-project#27]
It would be great to add commands to this template for code formatting.
Probably using a `clang-format` or some other suitable utility.

```
make fmt # formating code
make fmt-check # check format code
```

**Comment by bsamseth** [comment]
While I use clang-format myself on all projects, I'm hesitant to add it to the template for two reasons:

1. It adds a dependency (which is always a pain to make sure works all over)
2. It would inevitably trigger discussions/wants for particular style settings. 

That said, I wouldn't mind too much adding it in a cmake script in `cmake/Format.cmake`, and have it either not included in the top-level CMakeLists.txt by default, or make the script check for the presence of `clang-format`. In either case, there should _not_ be a `.clang-format` file in this template. You are welcome to make a PR and I'll more than likely merge it in. However, I won't be making the change myself, as I typically bake formatting into my editor rather than manually triggering it.

I'm closing this for now.
